#!/bin/bash


# kernel_cmdline <param> <default>
# Looks for a parameter on the kernel's boot-time command line.
#
# returns: 0 if param was found. Also prints its value if it was a K=V param.
#          1 if it was not. Also prints value passed as <default>
#
kernel_cmdline ()
{
    for param in $(/bin/cat /proc/cmdline); do
        case "${param}" in
            $1=*) echo "${param##*=}"; return 0 ;;
            $1) return 0 ;;
            *) continue ;;
        esac
    done
    [ -n "${2}" ] && echo "${2}"
    return 1
}


_do_locales ()
{
    XKEYMAP=""
    XVARIANT=""
    CKEYMAP=""
    case "${KEYMAP}" in
                     en_US)
                           #Amerikan English
                           XKEYMAP="us"
                           CKEYMAP="us"
                           ;;
                     en_GB)
                           #British English
                           XKEYMAP="gb"
                           CKEYMAP="uk"
                           ;;
                     be_BY)
                           #Belarusian
                           XKEYMAP="be"
                           CKEYMAP="be"
                           ;;
                     pt_BR)
                           #Brazilian Portuguese
                           XKEYMAP="br-abnt2"
                           CKEYMAP="br-abnt2"
                           ;;
                     bg_BG)
                           #Bulgarian
                           XKEYMAP="bg"
                           CKEYMAP="bg"
                           ;;
                     da_DK)
                           #Danish
                           XKEYMAP="dk"
                           CKEYMAP="dk"
                           ;;
                     fr_BE)
                           #Belgian
                           XKEYMAP="be-latin1"
                           CKEYMAP="be-latin1"
                           ;;
                     fr_BE)
                           #Belgian
                           XKEYMAP="be-latin1"
                           CKEYMAP="be-latin1"
                           ;;
                     fr_FR)
                           #French
                           XKEYMAP="fr"
                           CKEYMAP="fr"
                           ;;
                     fr_CA)
                           #Canadian
                           XKEYMAP="cf"
                           CKEYMAP="cf"
                           ;;
                     de_DE)
                           #German
                           XKEYMAP="de"
                           XVARIANT="nodeadkeys"
                           CKEYMAP="de"
                           ;;
                     is_IS)
                           #Icelandic
                           XKEYMAP="is"
                           CKEYMAP="is"
                           ;;
                     it_IT)
                           #Italian
                           XKEYMAP="it"
                           CKEYMAP="it"
                           ;;
                     nn_NO)
                           #Nynorsk
                           XKEYMAP="no"
                           CKEYMAP="no-latin1"
                           ;;
                     pl_PL)
                           #Polish
                           XKEYMAP="pl"
                           CKEYMAP="pl"
                           ;;
                     pt_PT)
                           #Portuguese
                           XKEYMAP="pt"
                           CKEYMAP="pt"
                           ;;
                     ro_RO)
                           #Romanian
                           XKEYMAP="ro"
                           CKEYMAP="ro"
                           ;;
                     ru_RU)
                           #Russian
                           XKEYMAP="ru"
                           CKEYMAP="ru"
                           ;;
                     es_AR)
                           #Argentinian
                           XKEYMAP="la-latin1"
                           CKEYMAP="la-latin1"
                           ;;
                     es_ES)
                           #Spanish
                           XKEYMAP="es"
                           CKEYMAP="es"
                           ;;
                     sv_SE)
                           #Swedish
                           XKEYMAP="sv-latin1"
                           CKEYMAP="sv-latin1"
                           ;;
                     tr_TR)
                           #Turkish
                           XKEYMAP="tr"
                           CKEYMAP="trq"
                           ;;
                     uk_UA)
                           #Ukrainian
                           XKEYMAP="ua"
                           CKEYMAP="ua"
                           ;;
    esac
    if [ "${XVARIANT}" != "" ] ; then 
       sed -i "s#Identifier \"evdev keyboard catchall\".*#&\n        Option \"XkbLayout\" \"${XKEYMAP}\"\n        Option \"XkbVariant\" \"${XVARIANT}\"#"       ${DESTDIR}/etc/X11/xorg.conf.d/10-evdev.conf
    else
       sed -i "s#Identifier \"evdev keyboard catchall\".*#&\n        Option \"XkbLayout\" \"${XKEYMAP}\"#"       ${DESTDIR}/etc/X11/xorg.conf.d/10-evdev.conf
    fi
    sed -i -e "s/^.*KEYMAP=.*/KEYMAP=${CKEYMAP}/" ${DESTDIR}/etc/vconsole.conf
}

